//-----------Load Outs-----------//

_allLoadOuts = [

//-----187th Rifleman-----//
["187th Rifleman",[["JLTS_DC15A_plastic","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",2,5]]],["187_Clone_Holster",[["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeWhite",2,1],["3AS_SmokeRed",1,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1]]],["187_Clone_Beltbag",[["JLTS_DC15A_mag",9,60]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Medic-----//
["187th Medic",[["JLTS_DC15S","","","",["JLTS_DC15S_mag",80],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Medic",[["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",9],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",10],["ACE_EarPlugs",2],["ACE_bodyBag",4],["ACE_IR_Strobe_Item",2],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",2,5]]],["187_Clone_Holster",[["JLTS_repairkit_weapon_mini",1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_SmokeWhite",2,1],["3AS_SmokeRed",1,1],["3AS_SmokePurple",2,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1],["3AS_ThermalDetonator",2,1],["JLTS_DC15S_mag",4,80]]],["187_Clone_Backpack_medic",[["ACE_elasticBandage",50],["ACE_packingBandage",20],["ACE_plasmaIV",5],["ACE_plasmaIV_500",8],["ACE_tourniquet",10],["ACE_epinephrine",10],["ACE_Morphine",10],["ACE_surgicalKit",1],["ACE_adenosine",5],["ACE_splint",10],["187th_Stimpack",10],["JLTS_DC15S_mag",3,80]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th RTO-----//
["187th RTO",[["JLTS_DC15S","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20]]],["187_Clone_Holster",[["3AS_ThermalDetonator",2,1],["3AS_SmokeWhite",3,1],["3AS_SmokeRed",2,1],["3AS_SmokePurple",2,1],["3AS_SmokeYellow",2,1],["3AS_SmokeOrange",2,1],["3AS_SmokeGreen",2,1],["3AS_SmokeBlue",2,1],["Luma_Green",2,1],["ACE_HandFlare_Red",2,1],["ACE_HandFlare_Green",2,1],["ACE_HandFlare_White",1,1]]],["187_Radio_Pack",[["JLTS_DC15S_mag",9,80]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemcTab","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Crewman-----//
["187th Crewman",[["JLTS_DC15S","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_splint",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",1,5]]],["187_Clone_Holster",[["MineDetector",1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["Luma_Green",2,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeGreen",1,1],["3AS_SmokeRed",1,1],["3AS_SmokeWhite",2,1]]],["187_Clone_Backpack",[["ToolKit",1],["JLTS_repairkit_weapon",1],["3AS_DetPack",3,1],["JLTS_DC15S_mag",9,80]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Engineer-----//
["187th Engineer",[["JLTS_DC15S","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_splint",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",1,5]]],["187_Clone_Holster",[["MineDetector",1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["Luma_Green",2,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeGreen",1,1],["3AS_SmokeRed",1,1],["3AS_SmokeWhite",2,1]]],["187_Clone_Backpack",[["ToolKit",1],["JLTS_repairkit_weapon",1],["3AS_DetPack",3,1],["JLTS_DC15S_mag",9,80]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Pilot-----//
["187th Pilot",[["JLTS_DC15S","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",10],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_tourniquet",4],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",1],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",4],["187th_Stimpack",5],["JLTS_DC17SA_mag",3,20],["JLTS_DC15A_mag",1,60]]],["187_Clone_Holster",[["ACE_Fortify",1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeWhite",2,1],["3AS_SmokeRed",1,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1],["JLTS_DC17SA_mag",1,20],["JLTS_DC15A_mag",5,60]]],["187_MiniRadio_Pack",[["JLTS_DC17SA_mag",2,20],["3AS_BaridumCore",2,1],["3AS_SmokeWhite",4,1],["JLTS_DC15A_mag",12,60],["JLTS_stun_mag_short",2,10],["JLTS_stun_mag_long",2,5]]],"187_Pilot_HelmetP2","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemcTab","JLTS_clone_comlink","ItemCompass","ACE_Altimeter",""]]],

//-----187th Grenadier-----//
["187th Grenadier",[["JLTS_DC15A_ugl_plastic","","","",["JLTS_DC15A_mag",60],["1Rnd_HE_Grenade_shell",1],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",1],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["ACE_HuntIR_monitor",1],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["ACE_SpraypaintRed",1],["ACE_SpraypaintGreen",1],["JLTS_DC17SA_mag",2,20]]],["187_Clone_Holster",[["ACE_wirecutter",1],["3AS_SmokeWhite",2,1],["3AS_SmokeGreen",2,1],["3AS_ThermalDetonator",6,1],["3AS_SmokeYellow",2,1]]],["187_Clone_Backpack",[["1Rnd_HE_Grenade_shell",15,1],["ACE_HuntIR_M203",2,1],["ACE_40mm_Flare_white",4,1],["UGL_FlareGreen_F",2,1],["JLTS_DC15A_mag",9,60],["UGL_FlareRed_F",2,1],["OPTRE_3Rnd_Smoke_Grenade_shell",4,3],["OPTRE_3Rnd_SmokeRed_Grenade_shell",3,3]]],"187_Clone_Helmet","OPTRE_HUD_w_Glasses",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemAndroid","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Support-----//
["187th Support",[["JLTS_Z6","","","",["JLTS_Z6_mag",300],[],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",3,5]]],["187_Clone_Holster",[["ACE_Tripod",1],["Chemlight_green",2,1],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeWhite",2,1],["3AS_SmokeRed",1,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1]]],["187_Clone_Beltbag",[["JLTS_Z6_mag",9,300]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter",""]]],

//-----187th AT-----//
["187th AT",[["JLTS_DC15A_plastic","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],["JLTS_RPS6","","","",["JLTS_RPS6_mag",1],[],""],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",2,5]]],["187_Clone_Holster",[["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_ThermalDetonator",2,1],["Luma_Green",2,1],["3AS_SmokeWhite",2,1],["3AS_SmokeGreen",1,1],["3AS_SmokeRed",1,1]]],["187_Clone_Backpack",[["JLTS_DC15A_mag",9,60],["JLTS_RPS6_mag",1,1],["JLTS_RPS6_HE_mag",1,1]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Breacher-----//
["187th Breacher",[["JLTS_DP23","","","",["JLTS_DP23_mag",20],[],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",2,5]]],["187_Clone_Holster",[["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["Luma_Green",2,1],["3AS_SmokeRed",1,1],["3AS_SmokeGreen",1,1],["3AS_SmokeWhite",2,1],["3AS_ThermalDetonator",2,1],["3AS_SonicDet",2,1]]],["187_Clone_Beltbag",[["JLTS_riot_shield_item",1],["JLTS_DP23_mag",9,20]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Marksman-----//
["187th Marksman",[["JLTS_DC15X","","","JLTS_DC15X_scope",["JLTS_DC15X_mag",15],[],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_Trooper",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",3,5]]],["187_Clone_Holster",[["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_SmokeWhite",2,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1],["3AS_SmokeRed",1,1]]],["187_Clone_Beltbag",[["ACE_Tripod",1],["JLTS_DC15X_mag",9,15]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th EOD-----//
["187th EOD",[["JLTS_DC15S","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],["JLTS_DC17SA","","JLTS_DC17SA_flashlight","",["JLTS_DC17SA_mag",20],["JLTS_stun_mag_long",5],""],["187th_Clone_EOD",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_CableTie",3],["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_Morphine",3],["ACE_plasmaIV_500",1],["ACE_tourniquet",3],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_epinephrine",3],["ACE_EarPlugs",2],["ACE_packingBandage",10],["ACE_bodyBag",1],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_splint",3],["187th_Stimpack",3],["JLTS_DC17SA_mag",2,20],["JLTS_stun_mag_long",2,5]]],["187_Clone_Holster",[["ACE_HandFlare_White",1,1],["ACE_HandFlare_Red",1,1],["ACE_HandFlare_Green",1,1],["3AS_ThermalDetonator",2,1],["3AS_SmokeWhite",2,1],["3AS_SmokeRed",1,1],["3AS_SmokeGreen",1,1],["Luma_Green",2,1]]],["187_Clone_Backpack_eod",[["JLTS_DC15S_mag",9,80]]],"187_Clone_Helmet","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]],

//-----187th Recruit-----//
["187th Recruit",[["JLTS_DC15A_plastic","","","",["JLTS_DC15A_mag",60],["JLTS_stun_mag_long",5],""],[],[],["187th_Clone_Recruit",[["ItemcTabHCam",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_wirecutter",1],["ACE_EntrenchingTool",1],["ACE_EarPlugs",2],["ACE_IR_Strobe_Item",2],["JLTS_repairkit_weapon_mini",1],["ACE_CableTie",3],["187th_Stimpack",3],["JLTS_stun_mag_long",2,5],["ACE_HandFlare_White",1,1],["ACE_HandFlare_Green",1,1],["3AS_SmokeWhite",2,1],["Luma_Green",2,1],["3AS_SmokeGreen",1,1]]],[],["187_Clone_Beltbag",[["ACE_quikclot",10],["ACE_elasticBandage",5],["ACE_Morphine",3],["ACE_packingBandage",10],["ACE_epinephrine",3],["ACE_plasmaIV_500",1],["ACE_bodyBag",1],["ACE_tourniquet",3],["ACE_splint",3],["JLTS_DC15A_mag",9,60]]],"187_Clone_Helmet_Recruit","",["JLTS_CloneBinocular","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","JLTS_clone_comlink","ItemCompass","ACE_Altimeter","JLTS_NVG_droid_chip_1"]]]

];

//----------LoadOuts End----------//

//-------add loadouts to ace default loadouts------
{[_x select 0,_x select 1] call ace_arsenal_fnc_addDefaultLoadout}forEach _allLoadOuts;